#!/bin/python3
import numpy as np
import cv2
cat=cv2.CascadeClassifier('cats.xml')
img=cv2.imread('cats.jpg')
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cats=cat.detectMultiScale(img)

for (x,y,w,h) in cats:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
cv2.imshow('dst',img)
cv2.waitKey(0)
